# -*- coding: utf-8 -*-
"""
Created on Mon Aug 01 01:11:02 2016
@author: DIP
"""

CONTRACTION_MAP = {
"ain't": "is not",
"aren't": "are not",
"can't": "cannot",
"can't've": "cannot have",
"'cause": "because",
"could've": "could have",
"couldn't": "could not",
"couldn't've": "could not have",
"didn't": "did not",
"doesn't": "does not",
"don't": "do not",
"hadn't": "had not",
"hadn't've": "had not have",
"hasn't": "has not",
"haven't": "have not",
"he'd": "he would",
"he'd've": "he would have",
"he'll": "he will",
"he'll've": "he will have",
"he's": "he is",
"how'd": "how did",
"how'd'y": "how do you",
"how'll": "how will",
"how's": "how is",
"I'd": "I would",
"I'd've": "I would have",
"I'll": "I will",
"I'll've": "I will have",
"I'm": "I am",
"I've": "I have",
"i'd": "i would",
"i'd've": "i would have",
"i'll": "i will",
"i'll've": "i will have",
"i'm": "i am",
"i've": "i have",
"isn't": "is not",
"it'd": "it would",
"it'd've": "it would have",
"it'll": "it will",
"it'll've": "it will have",
"it's": "it is",
"let's": "let us",
"ma'am": "madam",
"mayn't": "may not",
"might've": "might have",
"mightn't": "might not",
"mightn't've": "might not have",
"must've": "must have",
"mustn't": "must not",
"mustn't've": "must not have",
"needn't": "need not",
"needn't've": "need not have",
"o'clock": "of the clock",
"oughtn't": "ought not",
"oughtn't've": "ought not have",
"shan't": "shall not",
"sha'n't": "shall not",
"shan't've": "shall not have",
"she'd": "she would",
"she'd've": "she would have",
"she'll": "she will",
"she'll've": "she will have",
"she's": "she is",
"should've": "should have",
"shouldn't": "should not",
"shouldn't've": "should not have",
"so've": "so have",
"so's": "so as",
"that'd": "that would",
"that'd've": "that would have",
"that's": "that is",
"there'd": "there would",
"there'd've": "there would have",
"there's": "there is",
"they'd": "they would",
"they'd've": "they would have",
"they'll": "they will",
"they'll've": "they will have",
"they're": "they are",
"they've": "they have",
"to've": "to have",
"wasn't": "was not",
"we'd": "we would",
"we'd've": "we would have",
"we'll": "we will",
"we'll've": "we will have",
"we're": "we are",
"we've": "we have",
"weren't": "were not",
"what'll": "what will",
"what'll've": "what will have",
"what're": "what are",
"what's": "what is",
"what've": "what have",
"when's": "when is",
"when've": "when have",
"where'd": "where did",
"where's": "where is",
"where've": "where have",
"who'll": "who will",
"who'll've": "who will have",
"who's": "who is",
"who've": "who have",
"why's": "why is",
"why've": "why have",
"will've": "will have",
"won't": "will not",
"won't've": "will not have",
"would've": "would have",
"wouldn't": "would not",
"wouldn't've": "would not have",
"y'all": "you all",
"y'all'd": "you all would",
"y'all'd've": "you all would have",
"y'all're": "you all are",
"y'all've": "you all have",
"you'd": "you would",
"you'd've": "you would have",
"you'll": "you will",
"you'll've": "you will have",
"you're": "you are",
"you've": "you have",
"1":"",
"1st":"",
"first":"",
"2":"",
"2nd":"",
"second":"",
"3":"",
"3rd":"",
"third":"",
"4":"",
"fourth":"fourth",
"4":"",
"5th":"",
"5":"",
"6":"",
"7":"",
"8":"",
"9":"",
"0":"",
"aaaaa":"",######corrections
"abbout":"about",
"abilite":"ability",
"absutely":"absolutely",
"absute":"",
"absutely":"absolutely",
"abus":"",
"acceptng":"accepting",
"accesorie":"accessory",
"accommodatng":"accomodating",
"accomplied":"accomplished",
"accoutable":"accountable",
"accuacy":"accuracy",
"accuate":"accurate",
"actng":"acting",
"acton":"action",
"actvate":"activate",
"actvatng":"activating",
"actvaton":"activation",
"actve":"active",
"adapter":"adaptor",
"accout":"account",
"batery":"battery",
"baterie":"battery",
"baterys":"battery",
"bcuz":"because",
"beattie":"beauty",
"bien":"well",
"biz":"business",
"blu":"blue",
"bootloope":"bootloop",
"borthday":"birthday",
"botton":"bottom",
"boughthere":"bought here",
"bout":"about",
"bricke":"brick",
"briefthis":"brief this",
"bt":"bit",
"bf":"best friend",
"buen":"good",
"buttom":"button",
"ca":"",
"c":"",
"thesim":"the sim",
"amazae":"amazing",
"cmcrrypprdttlsol28":"",
"collecter":"collector",
"config":"configuration",
"costumer":"customer",
"coud":"could",
"counterfeit":"counterfit",
"cuz":"because",
"daybarely":"day barely",
"deceide":"decide",
"dec":"december",
"defenetly":"definitely",
"definetly":"definitely",
"definine":"define",
"descriprion":"description",
"deserve":"diserve",
"didntt":"did not",
"dificult":"difficult",
"direccion":"direction",
"disapointe":"dissapointed",
"dji":"",
"dont":"do not",
"e":"",
"ebwireless":"wireless",
"effecte":"effect",
"ein":"",
"el":"",
"e-mail":"email",
"enymore":"anymore",
"escelent":"excelent",
"especativas":"expectations",
"everydayteq":"everyday technology",
"excahnge":"exchange",
"excelente":"excellent",
"exellent":"excellent",
"experenice":"experience",
"extraordinario":"extraordinary",
"fb":"",
"feb":"february",
"feliz":"happy",
"fi":"",
"firt":"first",
"fm":"",
"for2":"",
"for299":"",
"forr":"for",
"frecuently":"frequent;y",
"freedompop":"freedom pop",
"frome":"from me",
"fst":"first",
"fubare":"fucked",
"fulfill":"fulfil",
"funciona":"functions",
"functionsgot":"functions got",
"g":"",
"galaxys":"galaxy",
"gen":"generation",
"ggl":"google",
"gime":"give me",
"givt":"gived",
"glaad":"glad",
"glas":"glass",
"glitche":"glitch",
"grandaugh":"granddaughter",
"grandma":"grandmother",
"grandpa":"grandfather",
"greatcalls":"great calls",
"gt":"",
"gusta":"like",
"hesitate":"hesitant",
"hrs":"hours",
"httpssmile":"smile",
"huaweis":"huawei",
"hubby":"husband",
"hubbys":"husband",
"ii":"",
"iii":"",
"im":"i am",
"imei":"",
"inlove":"in love",
"inmediatly":"immediately",
"inputte":"input",
"instal":"install",
"insync":"in sync",
"intal":"instal",
"intl":"",
"ir":"",
"ish":"",
"j":"",
"j1":"",
"j5":"",
"jabra":"",
"jun":"june",
"konke":"",
"1a":"",
"leeave":"leave",
"ler":"",
"lifeline786":"lifeline",
"lil":"little",
"lineageos":"",
"lookslike":"looks like",
"loooong":"long",
"lucki":"lucky",
"m8":"",
"m9":"",
"mae":"",
"mcrosd":"",
"mem":"",
"mic":"microphone",
"mom":"mother",
"morais":"",
"movil":"",
"msft":"microsoft",
"muy":"very",
"mvno":"",
"mvnos":"",
"mywit":"my wit",
"ne":"",
"nee":"",
"nic":"",
"nj":"",
"NOT_FOUND_INDEX":"",
"note5":"",
"note7":"",
"notificatoon":"notification",
"nov":"november",
"noy":"",
"nuf":"enough",
"nw":"new",
"ota":"",
"overheatingreturne":"overheating returned",
"PAD_INDEX":"",
"pasid":"poassword id",
"payton":"pay",
"perctly":"perfectly",
"phonak":"phone",
"phonenvironment":"phone environment",
"phoneon":"phone",
"pinion":"",
"prefromence":"performance",
"preinstalle":"installed",
"priv":"privacy",
"problemas":"problems",
"problemsgood":"problems good",
"problemsi":"problem",
"problemsjust":"problems just",
"producto":"product",
"prosthodontist":"",
"q10":"",
"qa":"",
"qi":"",
"r1":"",
"r1hd":"",
"reccommend":"recomend",
"reccommende":"recomend",
"recepcin":"reception",
"recepcion":"reception",
"recive":"receive",
"recivice":"receive",
"recomme":"recommend",
"recomendado":"recommend",
"recomme":"recommend",
"ref":"reference",
"refurb":"refurbished",
"retund":"refund",
"remive":"remind",
"rep":"representative",
"residido":"residue",
"rm1073":"",
"roote":"root",
"rtsupplies15":"supplies",
"s3":"",
"s4":"",
"s5":"",
"s6":"",
"s7":"",
"s8":"",
"s9":"",
"s10":"",
"saller":"",
"san":"",
"sansumg":"samsumg",
"satisfactoriamente":"satisfactory",
"savy":"savvy",
"scamme":"scam",
"scammy":"scam",
"sceptical":"skeptical",
"scereen":"screen",
"scrach":"scratch",
"scrache":"scratch",
"scruffe":"scrub",
"sd":"",
"se":"",
"seald":"sealed",
"serius":"serious",
"slugish":"sluggish",
"smartshopdeal":"smart shop deal",
"sol":"",
"sooooo":"so",
"sooooooooo":"so",
"specce":"spec",
"spect":"",
"striaght":"straight",
"stll":"still",
"tho":"",
"thou":"",
"thow":"",
"thru":"through",
"ti":"",
"tjose":"those",
"tks":"thanks",
"tlf":"",
"todo":"all",
"tracfonebut":"trackphone but",
"tracfone":"trackphone",
"turbocharging":"turbo charging",
"twigby":"",
"ughhhhh":"ugh",
"uhd":"",
"ui":"user interface",
"un":"",
"ur":"",
"usede":"",
"verizion":"verizon",
"yo":"",
"yr":"",
"yrs":"years",
"zenfone2":"zenfone",
"yea":"yes",
"yeah":"yes",
"xmas":"christmas",
"wowwww":"wow",
"woud":"would",
"workin":"working",
"woould":"would",
"wks":"",
"wirelesstechusa":"wireless tech usa",
"wirelessmaxinc":"wireless maxinc",
"wifes":"",
"whyyyy":"why",
"wanna":"want to",
"wam":"",
"wal":"",
"waaaaay":"",
"visable":"visible",
"vidoe":"video",
}